CREATE TABLE application (
        file_based boolean NOT NULL,
        hidden boolean NOT NULL,
        id integer generated by default as identity,
        privileged boolean,
        snapshot boolean NOT NULL,
        version timestamp(6) with time zone,
        application_version varchar(64),
        appng_version varchar(64),
        display_name varchar(64),
        name varchar(64) NOT NULL,
        time_stamp varchar(64),
        description varchar(8192),
        long_description oid,
        PRIMARY KEY (id),
        CONSTRAINT UK__APPLICATION__NAME UNIQUE (name)
    );

    CREATE TABLE authgroup (
        default_admin boolean,
        id integer generated by default as identity,
        version timestamp(6) with time zone,
        name varchar(64) NOT NULL,
        description varchar(8192),
        PRIMARY KEY (id),
        CONSTRAINT UK__AUTHGROUP__NAME UNIQUE (name)
    );

    CREATE TABLE authgroup_role (
        authgroup_id integer NOT NULL,
        role_id integer NOT NULL,
        PRIMARY KEY (authgroup_id, role_id)
    );

    CREATE TABLE database_connection (
        active boolean NOT NULL,
        id integer generated by default as identity,
        managed boolean NOT NULL,
        max_connections integer NOT NULL,
        min_connections integer NOT NULL check ((min_connections>=1)),
        site_id integer,
        version timestamp(6) with time zone,
        description varchar(255),
        driver_class varchar(255) NOT NULL,
        jdbc_url varchar(255) NOT NULL,
        name varchar(255) NOT NULL,
        type varchar(255) NOT NULL check ((type in ('MYSQL','MSSQL','POSTGRESQL','HSQL'))),
        username varchar(255) NOT NULL,
        validation_query varchar(255),
        password oid,
        PRIMARY KEY (id)
    );

    CREATE TABLE job_execution_record (
        duration integer,
        id integer generated by default as identity,
        run_once boolean,
        end_time timestamp(6),
        start_time timestamp(6),
        application varchar(255),
        job_name varchar(255),
        node varchar(255),
        result varchar(255),
        site varchar(255),
        triggername varchar(255),
        custom_data oid,
        stacktraces oid,
        PRIMARY KEY (id)
    );

    CREATE TABLE permission (
        application_id integer,
        id integer generated by default as identity,
        version timestamp(6) with time zone,
        description varchar(8192),
        name varchar(255) NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE platform_event (
        id integer generated by default as identity,
        created timestamp(6) with time zone,
        application varchar(255),
        context varchar(255),
        ev_type varchar(255) check ((ev_type in ('CREATE','UPDATE','DELETE','INFO','ERROR','WARN'))),
        ev_user varchar(255),
        event varchar(255),
        host_name varchar(255),
        origin varchar(255),
        request_id varchar(255),
        session_id varchar(255),
        PRIMARY KEY (id)
    );

    CREATE TABLE property (
        mandatory boolean,
        version timestamp(6) with time zone,
        description varchar(8192),
        default_value varchar(255),
        name varchar(255) NOT NULL,
        prop_type varchar(255) check ((prop_type in ('INT','DECIMAL','BOOLEAN','TEXT','PASSWORD','MULTILINE'))),
        value varchar(255),
        blob_value oid,
        clob_value oid,
        PRIMARY KEY (name)
    );

    CREATE TABLE repository (
        active boolean NOT NULL,
        id integer generated by default as identity,
        published boolean NOT NULL,
        strict boolean NOT NULL,
        version timestamp(6) with time zone,
        name varchar(64) NOT NULL,
        remote_repository_name varchar(64),
        description varchar(8192),
        digest varchar(255),
        mode varchar(255) check ((mode in ('ALL','STABLE','SNAPSHOT'))),
        type varchar(255) check ((type in ('LOCAL','REMOTE'))),
        accepted_certs oid,
        uri bytea,
        PRIMARY KEY (id),
        CONSTRAINT UK__REPOSITORY__NAME UNIQUE (name)
    );

    CREATE TABLE resource (
        application_id integer,
        id integer generated by default as identity,
        version timestamp(6) with time zone,
        description varchar(8192),
        checksum varchar(255),
        name varchar(255),
        type varchar(255) check ((type in ('BEANS_XML','JAR','XML','XSL','SQL','TPL','RESOURCE','ASSET','DICTIONARY','APPLICATION'))),
        bytes oid NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE role (
        application_id integer,
        id integer generated by default as identity,
        version timestamp(6) with time zone,
        name varchar(64) NOT NULL,
        description varchar(8192),
        PRIMARY KEY (id)
    );

    CREATE TABLE role_permission (
        permission_id integer NOT NULL,
        role_id integer NOT NULL,
        PRIMARY KEY (permission_id, role_id)
    );

    CREATE TABLE site (
        active boolean NOT NULL,
        create_repository boolean,
        id integer generated by default as identity,
        reload_count integer,
        version timestamp(6) with time zone,
        name varchar(64) NOT NULL,
        description varchar(8192),
        domain varchar(255) NOT NULL,
        host varchar(255) NOT NULL,
        PRIMARY KEY (id),
        CONSTRAINT UK__SITE__NAME UNIQUE (name),
        CONSTRAINT UK__SITE__HOST UNIQUE (host),
        CONSTRAINT UK__SITE__DOMAIN UNIQUE (domain)
    );

    CREATE TABLE site_application (
        active boolean NOT NULL,
        application_id integer NOT NULL,
        connection_id integer,
        deletion_mark boolean,
        reload_required boolean,
        site_id integer NOT NULL,
        PRIMARY KEY (application_id, site_id)
    );

    CREATE TABLE site_hostalias (
        site_id integer NOT NULL,
        hostname varchar(255)
    );

    CREATE TABLE sites_granted (
        application_id integer NOT NULL,
        granted_site_id integer NOT NULL,
        site_id integer NOT NULL,
        PRIMARY KEY (application_id, granted_site_id, site_id)
    );

    CREATE TABLE subject (
        id integer generated by default as identity,
        language varchar(3) NOT NULL,
        locked boolean,
        login_attempts integer,
        pw_change_policy smallint check ((pw_change_policy between 0 and 3)),
        expiry_date timestamp(6),
        last_login timestamp(6),
        pw_last_changed timestamp(6),
        version timestamp(6) with time zone,
        realname varchar(64) NOT NULL,
        description varchar(8192),
        digest varchar(255),
        email varchar(255),
        name varchar(255) NOT NULL,
        salt varchar(255),
        timezone varchar(255),
        type varchar(255) check ((type in ('LOCAL_USER','GLOBAL_USER','GLOBAL_GROUP'))),
        PRIMARY KEY (id),
        CONSTRAINT UK__SUBJECT__NAME UNIQUE (name)
    );

    CREATE TABLE subject_authgroup (
        group_id integer NOT NULL,
        subject_id integer NOT NULL
    );

    CREATE TABLE template (
        id integer generated by default as identity,
        version timestamp(6) with time zone,
        appng_version varchar(255),
        description varchar(255),
        display_name varchar(255),
        long_desc varchar(255),
        name varchar(255),
        template_version varchar(255),
        timestamp varchar(255),
        tpl_type varchar(255) check ((tpl_type in ('XSL','THYMELEAF'))),
        PRIMARY KEY (id)
    );

    CREATE TABLE template_resource (
        id integer generated by default as identity,
        template_id integer,
        file_version timestamp(6) with time zone,
        version timestamp(6) with time zone,
        checksum varchar(255),
        name varchar(255),
        bytes oid,
        PRIMARY KEY (id)
    );

    ALTER TABLE if exists authgroup_role 
       ADD CONSTRAINT FK__AUTHGROUP_ROLE__ROLE 
       FOREIGN KEY (role_id) 
       REFERENCES role;

    ALTER TABLE if exists authgroup_role 
       ADD CONSTRAINT FK__AUTHGROUP_ROLE__AUTHGROUP 
       FOREIGN KEY (authgroup_id) 
       REFERENCES authgroup;

    ALTER TABLE if exists database_connection 
       ADD CONSTRAINT FK__DATABASE_CONNECTION__SITE 
       FOREIGN KEY (site_id) 
       REFERENCES site;

    ALTER TABLE if exists permission 
       ADD CONSTRAINT FK__PERMISSION__APPLICATION 
       FOREIGN KEY (application_id) 
       REFERENCES application;

    ALTER TABLE if exists resource 
       ADD CONSTRAINT FK__RESOURCE__APPLICATION 
       FOREIGN KEY (application_id) 
       REFERENCES application;

    ALTER TABLE if exists role 
       ADD CONSTRAINT FK__ROLE__APPLICATION 
       FOREIGN KEY (application_id) 
       REFERENCES application;

    ALTER TABLE if exists role_permission 
       ADD CONSTRAINT FK__ROLE_PERMISSION__PERMISSION 
       FOREIGN KEY (permission_id) 
       REFERENCES permission;

    ALTER TABLE if exists role_permission 
       ADD CONSTRAINT FK__ROLE_PERMISSION__ROLE 
       FOREIGN KEY (role_id) 
       REFERENCES role;

    ALTER TABLE if exists site_application 
       ADD CONSTRAINT FK__SITE_APPLICATION__APPLICATION 
       FOREIGN KEY (application_id) 
       REFERENCES application;

    ALTER TABLE if exists site_application 
       ADD CONSTRAINT FK__SITE_APPLICATION__DATABASE_CONNECTION 
       FOREIGN KEY (connection_id) 
       REFERENCES database_connection;

    ALTER TABLE if exists site_application 
       ADD CONSTRAINT FK__SITE_APPLICATION__SITE 
       FOREIGN KEY (site_id) 
       REFERENCES site;

    ALTER TABLE if exists site_hostalias 
       ADD CONSTRAINT FK__SITE_HOSTALIAS__SITE 
       FOREIGN KEY (site_id) 
       REFERENCES site;

    ALTER TABLE if exists sites_granted 
       ADD CONSTRAINT FK__SITES_GRANTED__SITE 
       FOREIGN KEY (granted_site_id) 
       REFERENCES site;

    ALTER TABLE if exists sites_granted 
       ADD CONSTRAINT FK__SITES_GRANTED__SITE_APPLICATION 
       FOREIGN KEY (application_id, site_id) 
       REFERENCES site_application;

    ALTER TABLE if exists subject_authgroup 
       ADD CONSTRAINT FK__SUBJECT_AUTHGROUP__AUTHGROUP 
       FOREIGN KEY (group_id) 
       REFERENCES authgroup;

    ALTER TABLE if exists subject_authgroup 
       ADD CONSTRAINT FK__SUBJECT_AUTHGROUP__SUBJECT 
       FOREIGN KEY (subject_id) 
       REFERENCES subject;

    ALTER TABLE if exists template_resource 
       ADD CONSTRAINT FK__TEMPLATE_RESOURCE__TEMPLATE_ID 
       FOREIGN KEY (template_id) 
       REFERENCES template;